name: Mana Alchemy
favicon: null
layout_spectrum: 0.7332577283959836
typography_spectrum: 0.4649708718061447
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010123'
    - '#ece2d5'
    - '#daaa6a'
    - '#9d594a'
    - '#374341'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
