name: Mana Alchemy
favicon: null
layout_spectrum: 0.7332577283959836
typography_spectrum: 0.4649708718061447
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5354644758626819
  lightness: 0.49743538233451545
  saturation: 0.6527167968451977
  rhythmicContrast: 0.4974450943991542
purpose: []
